name: Autograding

on: [push]

jobs:
  autograde:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set permissions
      run: chmod +x test.sh

    - name: Create Feature Branch (if not exists)
      run: |
        if ! git show-ref --quiet refs/heads/feature; then
          git branch feature
        fi

    - name: Run Autograding Test
      run: ./test.sh
